services:
  squadcast:
    build:
      context: .
      dockerfile: dockerfile
    container_name: squadcast
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - SQUADCAST_DATA_DIR=/app/data
    volumes:
      - squadcast_data:/app/data

volumes:
  squadcast_data:
